# version: '3.8'

# services:
#   backend:
#     build:
#       context: ./project_backend
#       dockerfile: Dockerfile
#     container_name: django-backend
#     env_file: .env
#     volumes:
#       - ./project_backend:/app
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db

#   frontend:
#     build:
#       context: ./project_frontend
#       dockerfile: Dockerfile
#     container_name: react-frontend
#     ports:
#       - "3000:80"

#   db:
#     image: postgres:13
#     container_name: postgres-db
#     env_file: .env
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#       POSTGRES_DB: ${POSTGRES_DB}

#   nginx:
#     image: nginx:latest
#     container_name: nginx-server
#     volumes:
#       - ./nginx:/etc/nginx/conf.d
#     ports:
#       - "80:80"
#     depends_on:
#       - frontend
#       - backend

# volumes:
#   postgres_data:
