version: '3.8'

services:
  backend:
    build:
      context: ./project_backend
      dockerfile: Dockerfile
    container_name: django-backend-prod
    volumes:
      - ./project_backend:/app
    ports:
      - "8000:8000"
    env_file: .env.prod
    depends_on:
      - db

  frontend:
    build:
      context: ./project_frontend
      target: production
      dockerfile: Dockerfile
    container_name: react-frontend-prod
    volumes:
      - ./project_frontend:/app
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:16
    container_name: postgres-db-dev
    volumes:
      - postgres-db-dev:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
      - ./configs/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./configs/pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prod_database
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: pprod_postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    secrets:
      - postgres_password

volumes:
  postgres-db-dev:

secrets:
  postgres_password:
    file: ./secrets/postgres_password



volumes:
  postgres_data:
