# Generated by Django 5.0.6 on 2025-01-15 07:24

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggerPlantGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoggerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logger_name', models.CharField(max_length=100, unique=True)),
                ('alter_plant_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.loggerplantgroup')),
            ],
        ),
        migrations.CreateModel(
            name='PowerPlantDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=50)),
                ('system_id', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=100)),
                ('resource', models.CharField(choices=[('Solar', 'Solar'), ('Biomass', 'Biomass'), ('Wind', 'Wind')], default='Solar', max_length=100)),
                ('country_name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=12, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=12, max_digits=15)),
                ('altitude', models.DecimalField(decimal_places=4, max_digits=10)),
                ('azimuth', models.DecimalField(decimal_places=4, max_digits=10)),
                ('tilt', models.DecimalField(decimal_places=4, max_digits=10)),
                ('capacity_dc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity_ac', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.loggerplantgroup')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('system_name', 'system_id', 'group')},
            },
        ),
        migrations.CreateModel(
            name='UtilityPlantId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.CharField(max_length=100, unique=True)),
                ('alter_plant_id', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.loggerplantgroup')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoggerPowerGen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_gen', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('status', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('logger_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.loggercategory')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('logger_name', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MailNotificatione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_field', models.TextField(verbose_name='From')),
                ('to', models.TextField(blank=True, null=True, verbose_name='To')),
                ('date', models.DateField(blank=True, null=True)),
                ('mail_date_time', models.TextField(blank=True, null=True, verbose_name='Mail Date&Time')),
                ('subject', models.TextField(blank=True, null=True, verbose_name='Subject')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Body')),
                ('impact_category', models.CharField(blank=True, choices=[('Major', 'Major'), ('Minor', 'Minor'), ('None', 'None')], default='-', max_length=10, verbose_name='Impact Category')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='Memo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('mail_date_time', 'body')},
            },
        ),
        migrations.CreateModel(
            name='GisWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghi', models.DecimalField(decimal_places=3, max_digits=8)),
                ('gti', models.DecimalField(decimal_places=3, max_digits=8)),
                ('pvout', models.DecimalField(decimal_places=3, max_digits=8)),
                ('date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('power_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.powerplantdetail')),
            ],
            options={
                'unique_together': {('power_plant', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UtilityMonthlyRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('power_capacity_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sales_days', models.IntegerField(blank=True, null=True)),
                ('sales_electricity_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sales_amount_jpy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_jpy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('average_daily_sales_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rd', models.CharField(blank=True, max_length=7, null=True)),
                ('status', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.utilityplantid')),
            ],
            options={
                'unique_together': {('plant_id', 'contract_id', 'rd')},
            },
        ),
        migrations.CreateModel(
            name='UtilityMonthlyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_electricity_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('used_amount_jpy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_jpy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rd', models.CharField(blank=True, max_length=7, null=True)),
                ('status', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.utilityplantid')),
            ],
            options={
                'unique_together': {('plant_id', 'rd')},
            },
        ),
        migrations.CreateModel(
            name='UtilityDailyProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_production_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('production_date', models.DateField(blank=True, null=True)),
                ('rd', models.CharField(blank=True, max_length=7, null=True)),
                ('status', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.utilityplantid')),
            ],
            options={
                'unique_together': {('plant_id', 'production_date')},
            },
        ),
        migrations.CreateModel(
            name='CurtailmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('rd', models.CharField(blank=True, max_length=7, null=True)),
                ('status', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.utilityplantid')),
            ],
            options={
                'unique_together': {('plant_id', 'date')},
            },
        ),
    ]
